language: python
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- chmod +x ./build.sh
branch:
  only:
  - master
  - gh-pages
script: ./build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
